#!/usr/bin/env python3
"""
Import 2026 rookie rankings from dynasty_sf_2026_rookie_rankings into dynasty_prospects.
This script ensures the Scouting Portal displays the definitive 2026 rankings.
"""

import sys
import json
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent))

from config import config

def import_2026_rankings():
    """Import the provided 2026 rankings into dynasty_prospects."""
    supabase = config.get_supabase_client()
    if not supabase:
        print("❌ Failed to get Supabase client")
        return False

    # The data provided by the user
    raw_data = [
      {
        "rank": 17,
        "name": "Ja'Kobi Lane",
        "position": "WR",
        "school": "USC",
        "espn_id": 4870847,
        "id": 36,
        "tier": "Tier 4",
        "nfl_comparisons": "CeeDee Lamb, Davante Adams, Chris Olave",
        "display_tier": "First Round",
        "valuation": "54.30",
        "position_multiplier": "1.00",
        "tier_numeric": 4,
        "height": "76.00",
        "weight": "200.00",
        "class": None,
        "draft_year": None
      },
      {
        "rank": 16,
        "name": "Emmett Johnson",
        "position": "RB",
        "school": "Nebraska",
        "espn_id": None,
        "id": 35,
        "tier": "Tier 3",
        "nfl_comparisons": "Josh Jacobs, Javonte Williams, Cam Skattebo",
        "display_tier": "First Round",
        "valuation": "45.72",
        "position_multiplier": "0.80",
        "tier_numeric": 3,
        "height": "71.00",
        "weight": "200.00",
        "class": None,
        "draft_year": None
      },
      {
        "rank": 7,
        "name": "KC Concepcion",
        "position": "WR",
        "school": "TBD",
        "espn_id": 4870653,
        "id": 27,
        "tier": "Tier 2",
        "nfl_comparisons": "Puka Nacua, George Pickens, Drake London",
        "display_tier": "Elite Prospect",
        "valuation": "64.42",
        "position_multiplier": "1.00",
        "tier_numeric": 2,
        "height": None,
        "weight": None,
        "class": None,
        "draft_year": None
      },
      {
        "rank": 13,
        "name": "Demond Claiborne",
        "position": "RB",
        "school": "Wake Forest",
        "espn_id": None,
        "id": 32,
        "tier": "Tier 3",
        "nfl_comparisons": "Josh Jacobs, Javonte Williams, Cam Skattebo",
        "display_tier": "First Round",
        "valuation": "53.60",
        "position_multiplier": "0.80",
        "tier_numeric": 3,
        "height": "70.00",
        "weight": "195.00",
        "class": None,
        "draft_year": None
      },
      {
        "rank": 19,
        "name": "Nicholas Singleton",
        "position": "RB",
        "school": "Penn State",
        "espn_id": 4685555,
        "id": 20,
        "tier": "Tier 5",
        "nfl_comparisons": "Travis Etienne, Derrick Henry, Rico Dowdle",
        "display_tier": "First Round",
        "valuation": "39.33",
        "position_multiplier": "0.80",
        "tier_numeric": 5,
        "height": "71.00",
        "weight": "217.00",
        "class": "4",
        "draft_year": None
      },
      {
        "rank": 20,
        "name": "Jadarian Price",
        "position": "RB",
        "school": "Notre Dame",
        "espn_id": None,
        "id": 37,
        "tier": "Tier 4",
        "nfl_comparisons": "Travis Etienne, Derrick Henry, Rico Dowdle",
        "display_tier": "First Round",
        "valuation": "37.49",
        "position_multiplier": "0.80",
        "tier_numeric": 4,
        "height": "71.00",
        "weight": "209.00",
        "class": None,
        "draft_year": None
      },
      {
        "rank": 21,
        "name": "Duce Robinson",
        "position": "WR",
        "school": "Florida State",
        "espn_id": None,
        "id": 38,
        "tier": "Tier 5",
        "nfl_comparisons": "Chris Olave, Michael Pittman, A.J. Brown",
        "display_tier": "First Round",
        "valuation": "44.70",
        "position_multiplier": "1.00",
        "tier_numeric": 5,
        "height": "78.00",
        "weight": "222.00",
        "class": None,
        "draft_year": None
      },
      {
        "rank": 23,
        "name": "Michael Trigg",
        "position": "TE",
        "school": "Baylor",
        "espn_id": None,
        "id": 40,
        "tier": "Tier 5",
        "nfl_comparisons": "Tucker Kraft, Brock Bowers, Travis Kelce",
        "display_tier": "First Round",
        "valuation": "48.99",
        "position_multiplier": "1.20",
        "tier_numeric": 5,
        "height": "76.00",
        "weight": "240.00",
        "class": None,
        "draft_year": None
      },
      {
        "rank": 24,
        "name": "Hollywood Smothers",
        "position": "WR",
        "school": "TBD",
        "espn_id": None,
        "id": 41,
        "tier": "Tier 4",
        "nfl_comparisons": "Chris Olave, Michael Pittman, A.J. Brown",
        "display_tier": "First Round",
        "valuation": "39.08",
        "position_multiplier": "1.00",
        "tier_numeric": 4,
        "height": None,
        "weight": None,
        "class": None,
        "draft_year": None
      },
      {
        "rank": 25,
        "name": "Nyck Harbor",
        "position": "WR",
        "school": "South Carolina",
        "espn_id": None,
        "id": 42,
        "tier": "Tier 4",
        "nfl_comparisons": "Chris Olave, Michael Pittman, A.J. Brown",
        "display_tier": "First Round",
        "valuation": "37.45",
        "position_multiplier": "1.00",
        "tier_numeric": 4,
        "height": "77.00",
        "weight": "235.00",
        "class": None,
        "draft_year": None
      },
      {
        "rank": 22,
        "name": "Malachi Fields",
        "position": "WR",
        "school": "Notre Dame",
        "espn_id": None,
        "id": 39,
        "tier": "Tier 5",
        "nfl_comparisons": "Chris Olave, Michael Pittman, A.J. Brown",
        "display_tier": "First Round",
        "valuation": "42.69",
        "position_multiplier": "1.00",
        "tier_numeric": 5,
        "height": "76.00",
        "weight": "223.00",
        "class": None,
        "draft_year": None
      },
      {
        "rank": 26,
        "name": "Arch Manning",
        "position": "QB",
        "school": "Texas",
        "espn_id": 4870906,
        "id": 15,
        "tier": "Tier 5",
        "nfl_comparisons": "Geno Smith, Tua Tagovailoa, Cam Ward",
        "display_tier": "First Round",
        "valuation": "50.30",
        "position_multiplier": "1.40",
        "tier_numeric": 5,
        "height": "76.00",
        "weight": "219.00",
        "class": "2",
        "draft_year": None
      },
      {
        "rank": 27,
        "name": "Drew Allar",
        "position": "QB",
        "school": "Penn State",
        "espn_id": 4714771,
        "id": 19,
        "tier": "Tier 5",
        "nfl_comparisons": "Geno Smith, Tua Tagovailoa, Cam Ward",
        "display_tier": "First Round",
        "valuation": "48.32",
        "position_multiplier": "1.40",
        "tier_numeric": 5,
        "height": "77.00",
        "weight": "235.00",
        "class": "4",
        "draft_year": None
      },
      {
        "rank": 8,
        "name": "Chris Brazzell II",
        "position": "WR",
        "school": "Tennessee",
        "espn_id": 5091739,
        "id": 28,
        "tier": "Tier 2",
        "nfl_comparisons": "Puka Nacua, George Pickens, Drake London",
        "display_tier": "Elite Prospect",
        "valuation": "60.76",
        "position_multiplier": "1.00",
        "tier_numeric": 2,
        "height": "77.00",
        "weight": "200.00",
        "class": None,
        "draft_year": None
      },
      {
        "rank": 10,
        "name": "Eli Stowers",
        "position": "QB",
        "school": "TBD",
        "espn_id": 4431574,
        "id": 30,
        "tier": "Tier 2",
        "nfl_comparisons": "Jalen Hurts, Matthew Stafford, Dak Prescott",
        "display_tier": "Second Round",
        "valuation": "54.65",
        "position_multiplier": "1.40",
        "tier_numeric": 2,
        "height": None,
        "weight": None,
        "class": None,
        "draft_year": None
      },
      {
        "rank": 28,
        "name": "LaNorris Sellers",
        "position": "QB",
        "school": "South Carolina",
        "espn_id": None,
        "id": 3,
        "tier": "Tier 5",
        "nfl_comparisons": "Geno Smith, Tua Tagovailoa, Cam Ward",
        "display_tier": "First Round",
        "valuation": "46.48",
        "position_multiplier": "1.40",
        "tier_numeric": 5,
        "height": "75.00",
        "weight": "240.00",
        "class": "2",
        "draft_year": None
      },
      {
        "rank": 4,
        "name": "Justice Haynes",
        "position": "RB",
        "school": "Michigan",
        "espn_id": None,
        "id": 2,
        "tier": "Tier 1",
        "nfl_comparisons": "Christian McCaffrey, Jonathan Taylor, Jahmyr Gibbs",
        "display_tier": "Elite Prospect",
        "valuation": "62.29",
        "position_multiplier": "0.80",
        "tier_numeric": 1,
        "height": "71.00",
        "weight": "210.00",
        "class": "3",
        "draft_year": None
      },
      {
        "rank": 29,
        "name": "Cade Klubnik",
        "position": "QB",
        "school": "Clemson",
        "espn_id": 4685413,
        "id": 16,
        "tier": "Tier 5",
        "nfl_comparisons": "Geno Smith, Tua Tagovailoa, Cam Ward",
        "display_tier": "First Round",
        "valuation": "44.75",
        "position_multiplier": "1.40",
        "tier_numeric": 5,
        "height": "74.00",
        "weight": "210.00",
        "class": "4",
        "draft_year": None
      },
      {
        "rank": 30,
        "name": "Evan Stewart",
        "position": "WR",
        "school": "Oregon",
        "espn_id": 4685565,
        "id": 21,
        "tier": "Tier 5",
        "nfl_comparisons": "Troy Franklin, Zay Flowers, Rashid Shaheed",
        "display_tier": "First Round",
        "valuation": "30.82",
        "position_multiplier": "1.00",
        "tier_numeric": 5,
        "height": "71.00",
        "weight": "191.00",
        "class": "4",
        "draft_year": None
      },
      {
        "rank": 31,
        "name": "Garrett Nussmeier",
        "position": "QB",
        "school": "LSU",
        "espn_id": None,
        "id": 1,
        "tier": "Tier 5",
        "nfl_comparisons": "Geno Smith, Tua Tagovailoa, Cam Ward",
        "display_tier": "First Round",
        "valuation": "41.65",
        "position_multiplier": "1.40",
        "tier_numeric": 5,
        "height": "73.00",
        "weight": "205.00",
        "class": "4",
        "draft_year": None
      },
      {
        "rank": 32,
        "name": "Antonio Williams",
        "position": "WR",
        "school": "Clemson",
        "espn_id": 5081432,
        "id": 24,
        "tier": "Tier 5",
        "nfl_comparisons": "Troy Franklin, Zay Flowers, Rashid Shaheed",
        "display_tier": "First Round",
        "valuation": "28.75",
        "position_multiplier": "1.00",
        "tier_numeric": 5,
        "height": "71.00",
        "weight": "185.00",
        "class": "2",
        "draft_year": None
      },
      {
        "rank": 33,
        "name": "Eric Singleton Jr.",
        "position": "WR",
        "school": "Auburn",
        "espn_id": 5095360,
        "id": 23,
        "tier": "Tier 5",
        "nfl_comparisons": "Troy Franklin, Zay Flowers, Rashid Shaheed",
        "display_tier": "First Round",
        "valuation": "27.82",
        "position_multiplier": "1.00",
        "tier_numeric": 5,
        "height": "74.00",
        "weight": "201.00",
        "class": "4",
        "draft_year": None
      },
      {
        "rank": 34,
        "name": "Barion Brown",
        "position": "WR",
        "school": "LSU",
        "espn_id": None,
        "id": 9,
        "tier": "Tier 5",
        "nfl_comparisons": "Troy Franklin, Zay Flowers, Rashid Shaheed",
        "display_tier": "First Round",
        "valuation": "26.96",
        "position_multiplier": "1.00",
        "tier_numeric": 5,
        "height": "72.00",
        "weight": "190.00",
        "class": "4",
        "draft_year": None
      },
      {
        "rank": 35,
        "name": "Zachariah Branch",
        "position": "WR",
        "school": "Georgia",
        "espn_id": None,
        "id": 8,
        "tier": "Tier 5",
        "nfl_comparisons": "Troy Franklin, Zay Flowers, Rashid Shaheed",
        "display_tier": "First Round",
        "valuation": "26.15",
        "position_multiplier": "1.00",
        "tier_numeric": 5,
        "height": "73.00",
        "weight": "215.00",
        "class": "4",
        "draft_year": None
      },
      {
        "rank": 36,
        "name": "Eugene Wilson III",
        "position": "WR",
        "school": "Florida",
        "espn_id": None,
        "id": 5,
        "tier": "Tier 5",
        "nfl_comparisons": "Troy Franklin, Zay Flowers, Rashid Shaheed",
        "display_tier": "First Round",
        "valuation": "25.39",
        "position_multiplier": "1.00",
        "tier_numeric": 5,
        "height": "75.00",
        "weight": "213.00",
        "class": "4",
        "draft_year": None
      },
      {
        "rank": 37,
        "name": "Nico Iamaleava",
        "position": "QB",
        "school": "UCLA",
        "espn_id": None,
        "id": 14,
        "tier": "Tier 5",
        "nfl_comparisons": "Geno Smith, Tua Tagovailoa, Cam Ward",
        "display_tier": "Second Round",
        "valuation": "60.20",
        "position_multiplier": "1.40",
        "tier_numeric": 5,
        "height": "73.00",
        "weight": "195.00",
        "class": "2",
        "draft_year": None
      },
      {
        "rank": 38,
        "name": "Carson Beck",
        "position": "QB",
        "school": "Miami",
        "espn_id": None,
        "id": 12,
        "tier": "Tier 5",
        "nfl_comparisons": "Geno Smith, Tua Tagovailoa, Cam Ward",
        "display_tier": "Second Round",
        "valuation": "57.81",
        "position_multiplier": "1.40",
        "tier_numeric": 5,
        "height": "76.00",
        "weight": "220.00",
        "class": "4",
        "draft_year": None
      },
      {
        "rank": 39,
        "name": "Sam Leavitt",
        "position": "QB",
        "school": "Arizona State",
        "espn_id": None,
        "id": 13,
        "tier": "Tier 5",
        "nfl_comparisons": "Geno Smith, Tua Tagovailoa, Cam Ward",
        "display_tier": "Second Round",
        "valuation": "55.54",
        "position_multiplier": "1.40",
        "tier_numeric": 5,
        "height": "76.00",
        "weight": "220.00",
        "class": "4",
        "draft_year": None
      },
      {
        "rank": 40,
        "name": "Darius Taylor",
        "position": "RB",
        "school": "Minnesota",
        "espn_id": None,
        "id": 4,
        "tier": "Tier 5",
        "nfl_comparisons": "J.K. Dobbins, Kenneth Gainwell, TreVeyon Henderson",
        "display_tier": "Second Round",
        "valuation": "30.50",
        "position_multiplier": "0.80",
        "tier_numeric": 5,
        "height": "73.00",
        "weight": "215.00",
        "class": "4",
        "draft_year": None
      },
      {
        "rank": 41,
        "name": "Desmond Reid",
        "position": "RB",
        "school": "Pittsburgh",
        "espn_id": None,
        "id": 10,
        "tier": "Tier 5",
        "nfl_comparisons": "J.K. Dobbins, Kenneth Gainwell, TreVeyon Henderson",
        "display_tier": "Second Round",
        "valuation": "29.32",
        "position_multiplier": "0.80",
        "tier_numeric": 5,
        "height": "70.00",
        "weight": "210.00",
        "class": "4",
        "draft_year": None
      },
      {
        "rank": 9,
        "name": "Kaytron Allen",
        "position": "RB",
        "school": "Penn State",
        "espn_id": None,
        "id": 29,
        "tier": "Tier 2",
        "nfl_comparisons": "De'Von Achane, Bijan Robinson, James Cook",
        "display_tier": "Elite Prospect",
        "valuation": "45.96",
        "position_multiplier": "0.80",
        "tier_numeric": 2,
        "height": "71.00",
        "weight": "217.00",
        "class": None,
        "draft_year": None
      },
      {
        "rank": 18,
        "name": "Dante Moore",
        "position": "QB",
        "school": "Oregon",
        "espn_id": 4870921,
        "id": 11,
        "tier": "Tier 3",
        "nfl_comparisons": "Jaxson Dart, Jared Goff, Lamar Jackson",
        "display_tier": "First Round",
        "valuation": "72.30",
        "position_multiplier": "1.40",
        "tier_numeric": 3,
        "height": "75.00",
        "weight": "206.00",
        "class": "2",
        "draft_year": None
      },
      {
        "rank": 14,
        "name": "Chris Bell",
        "position": "WR",
        "school": "Kansas",
        "espn_id": 4869961,
        "id": 33,
        "tier": "Tier 3",
        "nfl_comparisons": "CeeDee Lamb, Davante Adams, Chris Olave",
        "display_tier": "First Round",
        "valuation": "63.48",
        "position_multiplier": "1.00",
        "tier_numeric": 3,
        "height": "70.00",
        "weight": "176.00",
        "class": None,
        "draft_year": None
      },
      {
        "rank": 5,
        "name": "Makai Lemon",
        "position": "WR",
        "school": "USC",
        "espn_id": None,
        "id": 6,
        "tier": "Tier 1",
        "nfl_comparisons": "Jaxon Smith-Njigba, Puka Nacua, George Pickens",
        "display_tier": "Elite Prospect",
        "valuation": "72.92",
        "position_multiplier": "1.00",
        "tier_numeric": 1,
        "height": "71.00",
        "weight": "200.00",
        "class": "4",
        "draft_year": None
      },
      {
        "rank": 6,
        "name": "Denzel Boston",
        "position": "WR",
        "school": "Washington",
        "espn_id": None,
        "id": 26,
        "tier": "Tier 2",
        "nfl_comparisons": "Puka Nacua, George Pickens, Drake London",
        "display_tier": "Elite Prospect",
        "valuation": "68.46",
        "position_multiplier": "1.00",
        "tier_numeric": 2,
        "height": "76.00",
        "weight": "209.00",
        "class": None,
        "draft_year": None
      },
      {
        "rank": 1,
        "name": "Jeremiyah Love",
        "position": "RB",
        "school": "Notre Dame",
        "espn_id": 4870808,
        "id": 17,
        "tier": "Tier 1",
        "nfl_comparisons": "Christian McCaffrey, Jonathan Taylor, Jahmyr Gibbs",
        "display_tier": "Elite Prospect",
        "valuation": "76.80",
        "position_multiplier": "0.80",
        "tier_numeric": 1,
        "height": "70.00",
        "weight": "205.00",
        "class": "3",
        "draft_year": None
      },
      {
        "rank": 3,
        "name": "Carnell Tate",
        "position": "WR",
        "school": "Ohio State",
        "espn_id": 4871023,
        "id": 18,
        "tier": "Tier 1",
        "nfl_comparisons": "Jaxon Smith-Njigba, Puka Nacua, George Pickens",
        "display_tier": "Elite Prospect",
        "valuation": "83.31",
        "position_multiplier": "1.00",
        "tier_numeric": 1,
        "height": "72.00",
        "weight": "199.00",
        "class": "3",
        "draft_year": None
      },
      {
        "rank": 2,
        "name": "Jordyn Tyson",
        "position": "WR",
        "school": "Arizona State",
        "espn_id": 4880281,
        "id": 22,
        "tier": "Tier 1",
        "nfl_comparisons": "Jaxon Smith-Njigba, Puka Nacua, Percy Harvin",
        "display_tier": "Elite Prospect",
        "valuation": "84.56",
        "position_multiplier": "1.00",
        "tier_numeric": 1,
        "height": "74.00",
        "weight": "205.00",
        "class": "4",
        "draft_year": None
      },
      {
        "rank": 15,
        "name": "Fernando Mendoza",
        "position": "QB",
        "school": "California",
        "espn_id": 4837248,
        "id": 34,
        "tier": "Tier 4",
        "nfl_comparisons": "Jaxson Dart, Jared Goff, Lamar Jackson",
        "display_tier": "First Round",
        "valuation": "84.29",
        "position_multiplier": "1.40",
        "tier_numeric": 2,
        "height": "77.00",
        "weight": "225.00",
        "class": None,
        "draft_year": None
      },
      {
        "rank": 11,
        "name": "Jonah Coleman",
        "position": "RB",
        "school": "Washington",
        "espn_id": 4702555,
        "id": 7,
        "tier": "Tier 2",
        "nfl_comparisons": "De'Von Achane, Bijan Robinson, James Cook",
        "display_tier": "Elite Prospect",
        "valuation": "41.40",
        "position_multiplier": "0.80",
        "tier_numeric": 2,
        "height": "69.00",
        "weight": "228.00",
        "class": "4",
        "draft_year": None
      },
      {
        "rank": 12,
        "name": "Kenyon Sadiq",
        "position": "TE",
        "school": "Oregon",
        "espn_id": 5083315,
        "id": 31,
        "tier": "Tier 2",
        "nfl_comparisons": "Trey McBride",
        "display_tier": "Elite Prospect",
        "valuation": "59.16",
        "position_multiplier": "1.20",
        "tier_numeric": 2,
        "height": "75.00",
        "weight": "245.00",
        "class": None,
        "draft_year": None
      }
    ]

    print("=" * 80)
    print("IMPORTING 2026 ROOKIE RANKINGS")
    print("=" * 80)

    # Transform data to match dynasty_prospects schema
    prospects = []
    for item in raw_data:
        prospect = {
            'name': item['name'],
            'position': item['position'],
            'school': item['school'],
            'espn_id': item['espn_id'],
            'draft_year': 2026,  # Force 2026
            'rank': item['rank'],
            'tier': item['tier'],
            'tier_numeric': item['tier_numeric'],
            'valuation': float(item['valuation']) if item['valuation'] else None,
            'position_multiplier': float(item['position_multiplier']) if item['position_multiplier'] else None,
            'grade_tier': item['display_tier'],  # Map display_tier to grade_tier
            'nfl_comparisons': item['nfl_comparisons'],
            'height': float(item['height']) if item['height'] else None,
            'weight': float(item['weight']) if item['weight'] else None,
            'class': item['class']
        }
        prospects.append(prospect)

    print(f"\n🔄 Transformed {len(prospects)} prospects")

    # Upsert to dynasty_prospects
    print("\n💾 Upserting to dynasty_prospects table...")
    try:
        result = supabase.table('dynasty_prospects').upsert(
            prospects,
            on_conflict='name,draft_year,position'
        ).execute()
        print(f"✅ Successfully imported {len(prospects)} 2026 prospects!")
    except Exception as e:
        print(f"❌ Error importing data: {str(e)}")
        return False

    return True

if __name__ == '__main__':
    success = import_2026_rankings()
    sys.exit(0 if success else 1)

